from django.db import migrations, models

class Migration(migrations.Migration):
    initial = True
    dependencies = []
    operations = [
        migrations.CreateModel(name='SiteSettings',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('company_name',models.CharField(default='Zentron Technologies',max_length=120)),('tagline',models.CharField(default='Dubai Licensed IT & Digital Solutions Company',max_length=180)),('phone',models.CharField(default='+971 52 512 2024',max_length=40)),('whatsapp',models.CharField(default='971525122024',max_length=40)),('email',models.EmailField(default='info@zentron.ae',max_length=254)),('address',models.CharField(default='Dubai, UAE',max_length=220)),('opening_hours',models.CharField(default='Available for business enquiries',max_length=180)),('footer_text',models.TextField(default='Helping businesses build a stronger online presence through websites, branding, marketing, and digital support.')),('updated_at',models.DateTimeField(auto_now=True))]),
        migrations.CreateModel(name='Industry',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120)),('slug',models.SlugField(unique=True)),('description',models.CharField(max_length=240)),('icon',models.CharField(default='◈',max_length=20)),('sort_order',models.PositiveIntegerField(default=0))]),
        migrations.CreateModel(name='Package',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=100)),('slug',models.SlugField(unique=True)),('label',models.CharField(blank=True,max_length=80)),('price',models.CharField(default='Custom',max_length=80)),('billing',models.CharField(blank=True,max_length=80)),('description',models.CharField(max_length=240)),('features',models.TextField(help_text='One feature per line')),('featured',models.BooleanField(default=False)),('sort_order',models.PositiveIntegerField(default=0))]),
        migrations.CreateModel(name='Project',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('title',models.CharField(max_length=160)),('category',models.CharField(max_length=100)),('description',models.TextField()),('image',models.ImageField(blank=True,null=True,upload_to='projects/')),('url',models.URLField(blank=True)),('is_featured',models.BooleanField(default=True)),('sort_order',models.PositiveIntegerField(default=0))]),
        migrations.CreateModel(name='QuoteRequest',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120)),('phone',models.CharField(max_length=40)),('email',models.EmailField(max_length=254)),('service',models.CharField(blank=True,max_length=120)),('message',models.TextField(blank=True)),('website',models.CharField(blank=True,max_length=200)),('created_at',models.DateTimeField(auto_now_add=True)),('is_contacted',models.BooleanField(default=False))]),
        migrations.CreateModel(name='Service',fields=[('id',models.BigAutoField(auto_created=True,primary_key=True,serialize=False,verbose_name='ID')),('name',models.CharField(max_length=120)),('slug',models.SlugField(unique=True)),('short_description',models.CharField(max_length=240)),('description',models.TextField()),('icon',models.CharField(default='✦',max_length=20)),('is_featured',models.BooleanField(default=True)),('sort_order',models.PositiveIntegerField(default=0))]),
    ]
